fga-gpp-mds/2018.1-Reabilitacao-Motora

README.md

testing the git kraken tool and updating readme to open source template

adding open source readme template to be completed throughout the project

---

docs/doxygen/documentation_and_examples.md
docs/doxygen/installation_and_running.md
docs/policies/branches.md
docs/policies/commits.md
docs/policies/issue.md
docs/policies/pull_request.md
docs/policies/style_sheet.md

Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>

Creating style sheet, commit and branch template files

---

.github/CODE_OF_CONDUCT.md

Criação do Código de Conduta
Criou-se o arquivo CODE_OF_CONDUCT.md contendo as regras de boa convivência dentro do projeto.
O Código de Conduta é um documento essencial para existirem regras definidas em relação ao comportamento dos contribuidores dentro dos ambientes do projeto.
Ex:

Criação do Código de Conduta

---

docs/wiki/Style-Sheet.md

A folha de estilo foi alterada para condizer com as atuais regras. Declaração de funções e estruturas de repetição sem espaco. 
Ex: 
```csharp
for(int i = 0; i<10; i++)
```
[Referência para issue](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/issues/42)
Ex:
Resolve #42

Correção da folha de estilo

---

.github/CODE_OF_CONDUCT.md
docs/wiki/Style-Sheet.md
docs/wiki/Termo-Abertura-Projeto.md

Atualização dos Documentos de EPS
Enviando atualizações dos documentos de EPS para a branch development.
Explique porque o PR é necessário, por exemplo:
Com a branch development atualizada, evita-se qualquer conflito maior, já que a branch em questão é a branch que serve de base para qualquer outra implementação.
Não há issues específicas relacionadas a este pull request, já que as contribuições para a branch eps_docs já foram consideradas no burndown.

Atualização dos Documentos de EPS

---

docs/contributing.md

Criação das instruções de contribuição
Criação de documento que indica como funciona o processo de contribuição para o projeto.
[Criar instruções de como contribuir](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/issues/57)
Instruções de como contribuir são fundamentais para atrair contribuidores externos.
Ex:
Resolve #57

Criação das instruções de contribuição

---

docs/wiki/Roadmap.md

Esse PR atualiza os topicos das sprints já existentes e completa o restante que faltava para a release 1.
Permite a finalização e check do feedback dado pela @RochaCarla em relação a alguns itens faltantes no roadmap 
Ex:
Resolve #63 .

Roadmap Release 1

---

docs/wiki/Prototipo.md

Protótipo de alta fidelidade.
Adiciona o um arquivo markdown contendo link e instruções para o protótipo de alta fidelidade.
[Protótipo de alta fidelidade](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/issues/58)
Adiciona o protótipo de alta fidelidade ao projeto, pois antes não havia um.
Ex:
Resolve #58 .

 Protótipo de Alta Fidelidade.

---

docs/index.html

Inicializando a configuração do github pages

Inicializando configuração do github pages

---

documentos.html
index.html

Esse PR adiciona duas paginas de navegação para a parte de documentação do git. Uma onde contem as informações dos contribuidores do projeto e outro onde contém os documentos atrelados.
Conforme a @RochaCarla solicitou uma melhor visualização dos documentos do projeto foram desenvolvidas essa paginas no github pages.

Adicionando design a pagina index de documentos no github.io

---

docs/wiki/canvas.md

Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>
#90  - Project Model Canvas
Adicionando Bussiness model canvas

Criando e iniciando versão 1.0

---

docs/wiki/Roadmap_Arquitetura.md

Roadmap de Arquitetura

---

docs/wiki/eap.md

Criação da Estrutura Analitica do Projeto que ajudaria EPS em como melhorar a organização e o entendimento do projeto. Além disso, essa estrutura auxilia na identificação de possíveis riscos em um plano.
Atualizar o repositorio com a EAP e assim fazer o link no github.io
Resolve #108.

Criando documento da EAP com o documento desenvolvido no google drive

---

docs/wiki/Atas-Reuniao.md
docs/wiki/AtasDojo.md

O objetivo desse pull request é passar as planilhas das atas de reunião para markdown e assim poder  aprensentar no github pages.
Para atulizar o github pages.
Resolve #112 .

Tradução das planilhas de ata de reuniao e dojo para markdown

---

docs/wiki/Documento-de-Visão.md

Documento de visão, que dá uma visão geral sobre o produto.
[Documento de visão](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/issues/17)
Para alinhar a branch do projeto um dos artefatos importantes do mesma.
Resolve #17 .

Documento de Visão

---

docs/wiki/riscos_do_projeto.md

Contém o documento que possui o levantamento inicial dos riscos e a sua pontuação inicial.
O documento feito nesta branch é essencial para o projeto.
Ex:

Metodologia de Controle de Riscos

---

.travis.yml
Reabilitacao-Motora/Assets/Scripts/travis_build.sh
Reabilitacao-Motora/Assets/Scripts/travis_deploy_dev.sh
Reabilitacao-Motora/Assets/Scripts/travis_deploy_master.sh
Reabilitacao-Motora/Assets/Scripts/travis_tests.sh

Agora existe uma API que recebe as builds do Travis e as disponibiliza por meio de um link que pode ser acessado desde que haja conexão com a internet.
[#166](#166)
Com a implementação do sistema, podemos agregar valor continuamente ao produto.
Resolve #166.

Implementação do Sistema de Deploy Contínuo

---

.travis.yml
Reabilitacao-Motora/Assets/Scripts/travis_build.sh
Reabilitacao-Motora/Assets/Scripts/travis_tests.sh
Reabilitacao-Motora/Assets/Scripts/travis_unity_key.sh
Reabilitacao-Motora/Assets/Scripts/travis_unity_return_key.sh
Reabilitacao-Motora/Assets/Scripts/travis_validation.sh

Modifica o script do travis para rodar os testes na integração contínua exibindo o log na tela do Travis
Automatização da esteira de entrega de valor contínuo do produto.

Adição da verificação de Testes na Integração Contínua

---

Reabilitacao-Motora/Assets/Scenes/Login.unity

… corrigir bug de não aparição.
Signed-off-by: Guilherme Siqueira <guilhersiqueira@gmail.com>
Co-authored-by: Guilherme Siqueira <guilhersiqueira@gmail.com>
Corrige o problema de ao entrar na pagina de login os campos de login e senha não estão corretamente identificados.
[Issue 214](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/issues/214)
Para identificar melhor os campos do login.
Ex:
Resolve #214 .

Login sem a identificação dos campos

---

Reabilitacao-Motora/Assets/Scenes/Graphs3.unity
Reabilitacao-Motora/ProjectSettings/ProjectSettings.asset

Corrige o bug de que não permitia voltar para a scene anterior à tela de movimento.
[Referência para US/UC](#216 )
Permite a saída da scene citada.
Resolve #216

 Botão de retorno não funciona - Tela de movimento

---

docs/identidade_visual.md

Atualiza a documentação do documento identidade_visual.md com dados referentes à nova identidade visual e direitos autorais das imagens e vetores utilizados.
[ Atualizar documentação referente à identidade visual](#241)
Resolve #241.

 Atualizar documentação referente à identidade visual. 

---

Reabilitacao-Motora/Assets/Scenes/Login.unity
Reabilitacao-Motora/Assets/Scripts/Menu/Login.cs
Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db.meta

Adiciona pop-up informando erro no login.
[209](#209 )
Resolve #209 .

Adicionando popup para informar erro no login

---

Reabilitacao-Motora/Assets/Prefabs/PhysioPrefab.prefab
Reabilitacao-Motora/Assets/Scenes/EndSession.unity
Reabilitacao-Motora/Assets/Scenes/ExercisesToReview.unity
Reabilitacao-Motora/Assets/Scenes/Login.unity
Reabilitacao-Motora/Assets/Scenes/Movements.unity
Reabilitacao-Motora/Assets/Scenes/MovementsToExercise.unity
Reabilitacao-Motora/Assets/Scenes/MovementsToReview.unity
Reabilitacao-Motora/Assets/Scenes/NewMovement.unity
Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist.unity
Reabilitacao-Motora/Assets/Scenes/NewSession.unity
Reabilitacao-Motora/Assets/Scenes/Patient.unity
Reabilitacao-Motora/Assets/Scenes/Session.unity
Reabilitacao-Motora/Assets/Scenes/Sessions.unity
Reabilitacao-Motora/Assets/Scenes/UpdatePatient.unity
Reabilitacao-Motora/Assets/Scripts/Buttons/Tab.cs
Reabilitacao-Motora/Assets/Scripts/Buttons/TabLogin.cs
Reabilitacao-Motora/Assets/Scripts/Buttons/TabLogin.cs.meta

Ao cadastrar-se vários pacientes/movimentos/exercícios/fisioterapeutas, os botões eram instanciados fora da tela, e não era possível a criação de parágrafos nas caixas de textos de observações. Ambos os problemas foram corrigidos com a criação de barras de rolagem.
[Referência para US/UC](#226)
Resolve o problema de botões instanciados fora da tela e da impossibilidade de escrever textos maiores nos inputfields de observações.
Ex:
Resolve #226.

 Comportar multíplos botões e preenchimento de inputfields com múltiplas linhas.

---

css/creative.css

Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>
Esse PR corrige o hint da navbar ao passar o mouse em cima de algum item
Deixar o layout mais responsivo
Resolve #248.

Corrigindo hint na navbar do github pages

---

Reabilitacao-Motora/Assets/Scenes/Login.unity

Signed-off-by: Arthur Diniz <arthurbdiniz@gmail.com>
A mensagem do popup antes não estava adequada para o usuário
Formatar a mensagem de popup para passar a informação correta ao usuário
Ex:
Resolve #296 .

Corrigindo mensagem de popup na tela de login

---

Reabilitacao-Motora/Assets/Scenes/MovementsToExercise.unity
Reabilitacao-Motora/Assets/Scenes/MovementsToReview.unity
Reabilitacao-Motora/Assets/Scenes/NewSession.unity
Reabilitacao-Motora/Assets/Scenes/Patient.unity
Reabilitacao-Motora/Assets/Scenes/Session.unity
Reabilitacao-Motora/Assets/Scenes/Sessions.unity
Reabilitacao-Motora/ProjectSettings/ProjectVersion.txt

Os títulos das telas foram retirados, cada uma de acordo com sua função.
[Títulos de telas](#305)
As telas agora tem mais coerência em seus titulos.
Resolve #305 .

Títulos de telas 

---

Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Adm.unity
Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Common.unity
Reabilitacao-Motora/Assets/Scenes/UpdatePatient.unity
Reabilitacao-Motora/Assets/Scenes/UpdatePhysiotherapist.unity
Reabilitacao-Motora/Assets/Scripts/Characters/AvatarChange.cs
Reabilitacao-Motora/Assets/Scripts/MaskedInputField.cs
Reabilitacao-Motora/Assets/Scripts/MaskedPhone.cs
Reabilitacao-Motora/Assets/Scripts/MaskedPhone.cs.meta

Corrige bugs no campo de telefone de todas as telas e apresenta uma máscara neste campo para melhor visualização por parte do usuário.
[Referência para US/UC](https://github.com/fga-gpp-mds/2018.1-Reabilitacao-Motora/issues/283)
Para corrigir um bug no campo de telefone.
Resolve #283 .

Campo telefone do paciente sem limitador e desformatado

---

Reabilitacao-Motora/Assets/Scenes/Patient.unity
Reabilitacao-Motora/Assets/Scenes/UpdatePatient.unity

Há um bug em que uma observação de um paciente cadastrado não podia ser visualizado depois, o mesmo aconteceu quando se editava tal observação.
[Bug de Observações do Paciente não estão sendo Visualizadas](#311)
Foram corrigidos os campos de observações tanto de Visualizar Paciente quando de Atualizar Paciente.
Ex:
Resolve #311

Corrigido o campo de observação do Paciente

---

Reabilitacao-Motora/Assets/Scripts/Characters/AvatarChange.cs

Kinect apresentava problemas de funcionamento que impossibilitava a captura do movimento quando seguia o fluxo da aplicação.
[Corrigir bug do mal funcionamento do Kinect](#257)
Corrige o problema do Kinect integrado com cada personagem selecionado da aplicação. Em todas as telas.
Resolve #257.

Corrigir bug do mal funcionamento do Kinect

---

Reabilitacao-Motora/Assets/Scripts/Instantiations/Exercise/instanciateExercise.cs

Foi pedido para fazer a remoção do ID dos exercícios listados. 
[ID Lista de Exercícios](#306 )
Foi removido o ID dos exercícios listados.
Ex:
Resolve #306

Removendo o id do Exercicio

---

Reabilitacao-Motora/Assets/Exercicios.meta
Reabilitacao-Motora/Assets/Movimentos.meta
Reabilitacao-Motora/Assets/Scenes/GraphsExerciciosSalvosPatient.unity
Reabilitacao-Motora/Assets/Scenes/GraphsMovimentoPhysio.unity
Reabilitacao-Motora/Assets/Scenes/GraphsReviewDuranteSessaoPatient.unity
Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity
Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPhysio.unity
Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPatient.unity
Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity
Reabilitacao-Motora/Assets/Scripts/Graphs/Label/DrawAreaLabel.cs
Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/InstanciateLabelsPhysio.cs
Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/MoveObjectXAxisPhysio.cs
Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Paciente/InstanciateLabelsPatient.cs
Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Paciente/MoveObjectXAxisPatient.cs
Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db.meta

Modifiquei script MoveObjectXAxis*.cs adicionando limitadores
[292](#292 )
Garante que o rótulo está realmente preso ao gráfico, não podendo extrapolar os limites do eixo X.
Resolve #292 .

Adicionando limite de range p labels não extrapolarem o grafico

---

docs/sprints/Planejamento-Sprint-14.md

Inclui no repositório o planejamento da sprint 14
Manter sempre atualizado a documentação de scrum master
Ex:

Adicionando o planejamento da sprint 14

---

Reabilitacao-Motora/Assets/Scenes/CharacterMenu.unity
Reabilitacao-Motora/Assets/Scripts/Buttons/ClipButtonToObject.cs
Reabilitacao-Motora/Assets/Scripts/Buttons/ClipButtonToObject.cs.meta

Os botões de escolha de personagem agora ficam alinhados independente da resolução ou escala na qual a aplicação está sendo executada.
[Alinhamento de botões na escolha do personagem](#276)
Melhora a experiência do usuário e aprimora visualmente o produto.
Resolve #276.

Alinhamento de botões na escolha do personagem

---

docs/sprints/Planejamento-Sprint-15.md

Este pull request adiciona o documento de abertura e planejamento da sprint 15.

Criação do planejamento da sprint 15

---

Reabilitacao-Motora/Assets/Tests/Editor/TestInstanciate.cs

Este pull request faz alteracões no teste de instanciação de session para que ele fique coerente com a refatoração do código.
[Referência para US/UC](#334 )
Resolve #334

Conserto do teste InstantiateSession

---

Reabilitacao-Motora/Assets/Actions/Man/PrepareExerciseMan.controller
Reabilitacao-Motora/Assets/Actions/Woman/CharacterWoman.controller

Corrige a animation controller para ter os movimentos corretos sendo executados nas telas do menu.

Correção das Animation Controllers

---

Reabilitacao-Motora/Assets/Scripts/travis_install.sh

Atualiza versão do Unity Editor no Travis para que elimine-se bugs fruto das versões antigas.
[Campo de texto com entrada de teclado duplicada](#270)
Resolve a issue de duplicação de caracteres no Ubuntu
Resolve #270.

Atualizando versão do Unity no Travis

---

Reabilitacao-Motora/Assets/Scenes/NewPatient.unity

Corrige bug na máscara de data de nascimento na scene de cadastro de paciente.
Para que o bug não ocorra mais e a visualização da data de nascimento seja a mais correta.
Resolve #361 .

Corrigindo bug na máscara de data de nascimento do cadastro de paciente.

---

Reabilitacao-Motora/Assets/Scenes/Session.unity

O botão de voltar da scene session foi alterado de posição, possibilitando o click independente da resolução da tela.
[Bug no botão de voltar](#363)
Agora é possivel voltar  independente da resolução da tela., pois o botão não fica mais atrás da divisão.
Ex:
Resolve #363.

Resolvendo bug do botão na scene session

---

UDP/measureUDPLatency.py

Criação de um script em Python que se comunica com as duas interfaces UDP para medir o tempo de resposta entre elas.
Torna pública a ferramenta de medição, possibilitando a conferência pelo usuário.
Ex:

Script para medir latência do sensor UDP
